### ISSUE TITLE
Create examples

### ISSUE THREAD

**Issue by iScrE4m** [iScrE4m/pyCardDeck#1]
There should be examples of usage. 

These examples don't have to containt the game logic, but only the parts where pyCardDeck is relevant

By writing those, we'll:

- show how a to have a nice card object that will utilize the library
- highlight what is missing in the library
- check if the library is pleasurable to work with (very important)

Examples to write: 

- [x] Poker
- [x] Exploding Kittens
- [x] Blackjack
- [x] MtG or Hearthstone (drafting or deck management)
- [ ] Old maid
- [ ] Mau Mau
- [ ] Quartets or Go Fish
- [ ] ~~War~~

**Comment by iScrE4m** [comment]
Written first example fe63c3e113760bd6732d4b09e0049c1a5c129ed3

**Comment by iScrE4m** [comment]
Explding kittens 9e8187e8e0391b8fac91c6d06ef68c0d72169f7f: and e1242d7289c4f25329ddff8867fe87303e02f4cb

**Comment by iScrE4m** [comment]
War scraped, because it showcases nothing special

**Comment by cranndarach** [comment]
I made a blackjack example in pull request #9

**Comment by iScrE4m** [comment]
Judging by the examples written, there isn't much else to be done that would showcase what hasn't been showcased. If anyone wants to improve the existing examples, feel free. I'm closing this issue.
