### ISSUE TITLE
standard_deck.yml not included with pip release

### ISSUE THREAD

**Issue by cranndarach** [iScrE4m/pyCardDeck#12]
When using the `pyCardDeck.deck.Deck.load_standard_deck()` function, the following error occurred: 

```python
Traceback (most recent call last):
  File "examples/blackjack.py", line 175, in <module>
    Player("Simon")])
  File "examples/blackjack.py", line 26, in __init__
    self.deck.load_standard_deck()
  File "/home/$USER/anaconda3/lib/python3.5/site-packages/pyCardDeck/deck.py", line 378, in load_standard_deck
    data = yaml.load(open(location)).__dict__
FileNotFoundError: [Errno 2] No such file or directory: '/home/$USER/anaconda3/lib/python3.5/site-packages/pyCardDeck/standard_deck.yml'
```

I checked and confirmed that it was not there, and pasted the file from this repository into the pip-installed directory, and it ran correctly.

**Comment by iScrE4m** [comment]
Whoa, thanks for pointing this out. I'll try and find time to figure it out, MANIFEST.in obviously isn't working as I thought it would. If you'd like to have a lok at it too, feel free.

**Comment by cranndarach** [comment]
It might be a matter of adding an argument `include_package_data=True` to `setup.py`'s `setup()` call, but I'm not really familiar with pip and haven't gotten a chance to test that hypothesis much yet. These are what led me to that guess: ([x](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files)|[x](http://stackoverflow.com/questions/3596979/manifest-in-ignored-on-python-setup-py-install-no-data-files-installed))

**Comment by iScrE4m** [comment]
Indeed, that did the trick. Thanks!
