### ISSUE TITLE
JSON Import and Export

### ISSUE THREAD

**Issue by iScrE4m** [iScrE4m/pyCardDeck#4]
It's good to have the ability to export a deck into a JSON format(file) and later import from the very same file, so that decks can be easily shared and replicated.

**Comment by pmccauley1994** [comment]
It might be better to use a yaml file format.
YAML is much easier to read than JSON and can be read in and indexed like a dictionary much like json can be
This functionality is provided by PyYaml

**Comment by iScrE4m** [comment]
I'd go for JSON first, because it's more known (popular) and new programmers are likely to learn JSON first, however I'm not against YAML, if you want to implement that, more options are always good!

**Comment by pmccauley1994** [comment]
I agree with using JSON based on the fact it is more popular. 
In my experience I found YAML to use although in this scenario it wouldn't matter which.
It could be possible to use both and automatically detect which based on file type.
I will began implementing this

**Comment by iScrE4m** [comment]
With YAML export existing, we should probably be smart with our import/export to support both easily and have a beautiful api for users.

Export function should:
- return either yaml or json based on a required positional argument
- have keyword argument to_file with true/false and only export to a file when set to true
   
Import function should:
- recognize the contents of the file and raise an exception when the format is not recognized
- also know when to import from file and when it|s being passed pure yaml/json

**Comment by iScrE4m** [comment]
I'm almost done with this, don't pick this up ;)
