### ISSUE TITLE
unittest to py.test

### ISSUE THREAD

**Issue by iScrE4m** [iScrE4m/pyCardDeck#6]
I started writing tests with classic unittest.TestCase in mind, they should be rewritten into py.test format (just functions and asserts if I understand py.test correctly) :D 

While at it, test coverage should be increased back to 100% ;)

**Comment by pmccauley1994** [comment]
I will write the tests for save/loading decks and some others. 
Will start on it some time this week
Real work takes priority :)

**Comment by iScrE4m** [comment]
I actually already have them done, just porting the rest now. Feel free to edit/upgrade them later though!
